# Lancer tous les tests
test:
	pytest -v

# Lancer uniquement les tests unitaires et intégration (sans performance)
unit_test:
	pytest -v -m "not perf"

# Lancer uniquement les tests de performance
perf_test:
	pytest -v -m "perf"
